apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: tehami/my-alpine:latest
          command: ["tail", "-f", "/dev/null"] # Keep the container running
      serviceAccountName: job-creator-sa

