apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator-role
subjects:
- kind: ServiceAccount
  name: job-creator-sa

