apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-events-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-events-be
  template:
    metadata:
      labels:
        app: k8s-events-be
    spec:
      containers:
      - name: k8s-events-be
        image: tehami/k8s-events-be:0.0.2
        ports:
        - containerPort: 8000
      serviceAccountName: job-creator-sa
